# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cldr}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven Fuchs"]
  s.date = %q{2010-01-09}
  s.description = %q{Ruby library for exporting and using data from CLDR}
  s.email = %q{svenfuchs@artweb-design.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile",
     "TODO"
  ]
  s.files = [
    "LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/cldr.rb",
     "lib/cldr/data.rb",
     "lib/cldr/data/base.rb",
     "lib/cldr/data/calendars.rb",
     "lib/cldr/data/calendars/gregorian.rb",
     "lib/cldr/data/currencies.rb",
     "lib/cldr/data/delimiters.rb",
     "lib/cldr/data/languages.rb",
     "lib/cldr/data/numbers.rb",
     "lib/cldr/data/plurals.rb",
     "lib/cldr/data/plurals/cldr_grammar.treetop",
     "lib/cldr/data/plurals/grammar.rb",
     "lib/cldr/data/plurals/rules.rb",
     "lib/cldr/data/territories.rb",
     "lib/cldr/data/units.rb",
     "lib/cldr/export.rb",
     "lib/cldr/export/ruby.rb",
     "lib/cldr/export/yaml.rb",
     "lib/cldr/format.rb",
     "lib/cldr/format/base.rb",
     "lib/cldr/format/fraction.rb",
     "lib/cldr/format/integer.rb",
     "lib/cldr/format/number.rb",
     "lib/cldr/format/numeric.rb",
     "lib/core_ext/hash/deep_merge.rb",
     "lib/core_ext/hash/deep_stringify_keys.rb",
     "lib/core_ext/hash/symbolize_keys.rb",
     "lib/core_ext/string/camelize.rb",
     "lib/core_ext/string/underscore.rb",
     "test/all.rb",
     "test/data/all.rb",
     "test/data/calendars_test.rb",
     "test/data/currencies_test.rb",
     "test/data/delimiters_test.rb",
     "test/data/languages_test.rb",
     "test/data/numbers_test.rb",
     "test/data/plurals_test.rb",
     "test/data/territories_test.rb",
     "test/data/units_test.rb",
     "test/export_test.rb",
     "test/formats/all.rb",
     "test/formats/format_test.rb",
     "test/formats/fraction_test.rb",
     "test/formats/integer_test.rb",
     "test/formats/number_test.rb",
     "test/formats/numeric_test.rb",
     "test/formats/rails_compat/all.rb",
     "test/formats/rails_compat/format_integer_test.rb",
     "test/formats/rails_compat/format_number_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/svenfuchs/cldr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library for exporting and using data from CLDR}
  s.test_files = [
    "test/all.rb",
     "test/data/all.rb",
     "test/data/calendars_test.rb",
     "test/data/currencies_test.rb",
     "test/data/delimiters_test.rb",
     "test/data/languages_test.rb",
     "test/data/numbers_test.rb",
     "test/data/plurals_test.rb",
     "test/data/territories_test.rb",
     "test/data/units_test.rb",
     "test/export_test.rb",
     "test/formats/all.rb",
     "test/formats/format_test.rb",
     "test/formats/fraction_test.rb",
     "test/formats/integer_test.rb",
     "test/formats/number_test.rb",
     "test/formats/numeric_test.rb",
     "test/formats/rails_compat/all.rb",
     "test/formats/rails_compat/format_integer_test.rb",
     "test/formats/rails_compat/format_number_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

